// User Events
export const REPLACE_USER_EVENTS = 'REPLACE_USER_EVENTS';
export const ADD_USER_EVENT = 'ADD_USER_EVENT';
export const DELETE_USER_EVENTS = 'DELETE_USER_EVENTS';

// Filters
export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';

export const ENABLE_FILTER = 'ENABLE_FILTER';
export const DISABLE_FILTER = 'DISABLE_FILTER';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';

export const ADD_FILTER_OPTION = 'ADD_FILTER_OPTION';
export const REMOVE_FILTER_OPTION = 'REMOVE_FILTER_OPTION';

export const ENABLE_FILTER_OPTION = 'ENABLE_FILTER_OPTION';
export const DISABLE_FILTER_OPTION = 'DISABLE_FILTER_OPTION';
export const TOGGLE_FILTER_OPTION = 'TOGGLE_FILTER_OPTION';

export const SELECT_ALL_FILTER_OPTIONS = 'SELECT_ALL_FILTER_OPTIONS';
export const SELECT_NONE_FILTER_OPTIONS = 'SELECT_NONE_FILTER_OPTIONS';

// Events
export const ADD_EVENT = 'ADD_EVENT';
export const ADD_EVENTS = 'ADD_EVENTS';
export const REPLACE_EVENTS = 'REPLACE_EVENTS';

// Admin Events
export const ADD_ADMIN_EVENT = 'ADD_ADMIN_EVENT';
export const ADD_ADMIN_EVENTS = 'ADD_ADMIN_EVENTS';
export const REPLACE_ADMIN_EVENTS = 'REPLACE_ADMIN_EVENTS';

// Available Columns
export const REPLACE_AVAILABLE_COLUMNS = 'REPLACE_COLUMN';
